import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Header from "@/components/main/Header";
import Footer from "@/components/main/Footer";
import { SessionProvider } from "next-auth/react";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dmSans",
});

const beatrice = localFont({
  variable: "--font-beatrice",
  src: "../../public/fonts/BeatriceTrial-Medium.ttf"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`${dm_sans.variable} ${beatrice.variable}`}>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
