import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Header from "@/components/main/Header";
import Footer from "@/components/main/Footer";
import { AuthProvider } from "@/contexts/AuthContext";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dmSans",
});

const beatrice = localFont({
  variable: "--font-beatrice",
  src: [
    {
      path: "../../public/fonts/BeatriceTrial-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/BeatriceTrial-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/BeatriceTrial-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/BeatriceTrial-Semibold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${dm_sans.variable} ${beatrice.variable} overflow-x-hidden`}
        >
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
